// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-5Yr-CrX8rhGAJIgOY5rRWRt50yXx9so',
    appId: '1:279536954313:web:5d53d8c9b25682d39bd618',
    messagingSenderId: '279536954313',
    projectId: 'mindrush-d92c3',
    authDomain: 'mindrush-d92c3.firebaseapp.com',
    storageBucket: 'mindrush-d92c3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2wjdETBu0ztXqrAm813dEz39nD-QquZc',
    appId: '1:279536954313:android:492dad5ef847b4569bd618',
    messagingSenderId: '279536954313',
    projectId: 'mindrush-d92c3',
    storageBucket: 'mindrush-d92c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI4lZfC9ciJKZ5Dnz4-BHMCzLpS1KLl6U',
    appId: '1:279536954313:ios:670c890daa06c07a9bd618',
    messagingSenderId: '279536954313',
    projectId: 'mindrush-d92c3',
    storageBucket: 'mindrush-d92c3.firebasestorage.app',
    iosBundleId: 'com.mindrush.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBI4lZfC9ciJKZ5Dnz4-BHMCzLpS1KLl6U',
    appId: '1:279536954313:ios:b5c12852b157ce229bd618',
    messagingSenderId: '279536954313',
    projectId: 'mindrush-d92c3',
    storageBucket: 'mindrush-d92c3.firebasestorage.app',
    iosBundleId: 'com.example.mindRush',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-5Yr-CrX8rhGAJIgOY5rRWRt50yXx9so',
    appId: '1:279536954313:web:5c6a4c4648fc5a5d9bd618',
    messagingSenderId: '279536954313',
    projectId: 'mindrush-d92c3',
    authDomain: 'mindrush-d92c3.firebaseapp.com',
    storageBucket: 'mindrush-d92c3.firebasestorage.app',
  );
}
